---
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-learn-python-config
  labels:
    helm.sh/chart: learn-python-0.1.0
    app.kubernetes.io/name: learn-python
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/part-of: "learn-python"
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
data:
  EXTRA_DUMMY: VALUE
